### ISSUE TITLE
Crashpad failed to start handler

### ISSUE THREAD

**Issue by Fahad-Hey** [modularml/mojo#984]
### Where is the problem?

Crashpad

### What can we do better?

suggest to us how to solve this type of error :
[11386:11386:20231003,212317.111937:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[11384:11384:20231003,212317.112988:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler **(how to fix this error)**

**Comment by Tang-hubert** [comment]
For me, just ignore it~

**Comment by Tang-hubert** [comment]
Oh! and dont forget to try other networks.

**Comment by shilisi** [comment]
I also have the same problem, I did not find a solution in the community, do you know how to solve it?

**Comment by zbowling** [comment]
Are you perhaps running on WSL1? can you check to see if you are running under WSL1 or WSL2? Also can list the distro and version in WSL you are using? There are known issues with WSL1.

**Comment by attiouimehdi** [comment]
I have the same issue for installing mojo on windows 10 ( i use ubuntu 22.4 lts with wsl).
i use a wsl v0.81.8 on visual studio code. 
the error returned after the command " modular install mojo" is
[31:31:20231019,221912.385083:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[29:29:20231019,221912.386116:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
modular: error: invalid manifest: targets manifest was not an object
modular version is 0.2.1.

**Comment by wangwendong1024** [comment]
wsl --update 
my wsl verison :
Administrator@DESKTOP C:\Users\Administrator
# wsl -v
WSL 版本： 1.2.5.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.19045.3570

After upgrading wsl to the latest version, run ubuntu20.04 of wsl to reinstall the modular

**Comment by smuniraj2018** [comment]
Please update to WSL2. That should hopefully resolve the issue

**Comment by mohan-676** [comment]
You can either Update your wsl or just try to install it by using "sudo apt install wsl"
My issue was resolved by this and installed mojo sucessfully

**Comment by sohaha** [comment]
Mine is WSL2 but it doesn't work

**Comment by HasCodingSpace** [comment]
@attiouimehdi @shilisi @Fahad-Hey  did u find any fix to the errors?

**Comment by realnihal** [comment]
I am running this on an m1, still getting the same issue. Any suggestions?

**Comment by realnihal** [comment]
Running it with Sudo Privilege seemed to solved the issue

**Comment by Swag-With-Jal** [comment]
same error for me also:
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: while locating crashpad handler: unable to locate crashpad handler executable

**Comment by Swag-With-Jal** [comment]
There are few things like giving path which he missed.....while installing mojo you have to give this(export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH") path and while using jupyter lab use this (export PATH="$HOME/.local/bin:$PATH") path in vscode teminal...without it jupter lab will not work.

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.

**Comment by rcghpge** [comment]
hey group. I ran into the same Crashpad bugs. Looked around. Is this by chance Google's stack? I ran into some Google Crashpad documentation online

![Image](https://github.com/user-attachments/assets/2e91d1b4-1773-4da9-ae79-2671ecabda5c)
